### ISSUE TITLE
Timestamps in wrong key

### ISSUE THREAD

**Issue by joao** [sammorrisdesign/interactive-feed#8]
In the archived data timestamps are being placed in the wrong key, 'image' instead of 'timestamp', at least for The New York Times - didn't check all of the publications. Behaviour began around 23rd September.

Not confortable with the codebase, so not sending a pull request, but can try to have a look if needed.

![Screenshot 2024-10-31 at 14 52 25](https://github.com/user-attachments/assets/714a7227-afc9-4d85-9a68-1b425779e6b3)

**Comment by sammorrisdesign** [comment]
Ah that should be fixed now. the `Article` class required individual arguments in a specific order. I've now made it so `Article` is handed an object that it unpacks in the constructor. It looks like only Washington Post and New York Times articles are impacted.

**Comment by joao** [comment]
Thank you :)  
Everything seems to be working perfectly now.
